# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 02:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2012, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
